### PR TITLE
Spin fits

### PR DESCRIPTION
**Pull request by phajy**
Fitting the spin of MCG-6-30-15 using XMM and NuSTAR merged data for illustrative purposes rather than for publication

### CODE REVIEW

**Comment by phajy** [comment]
For simplicity I decided to use merged data sets. These are perfectly fine for the purposes of the presentation although for publication we should jointly fit all the data sets.

A few modifications I need to make before this PR is ready for merging

- [x] The plots need to be adjusted. The log scale doesn't seem to be working properly and I need to change the colours of each plot.
- [ ] I forgot that MCG-6-30-15 is at a slight redshift, $z = 0.007749$ so the iron line would be redshifted from $6.4 \text{\ keV} \to 6.35 \text{\ keV}$.
- [ ] Need to calculate the error interval on parameters. Ultimately MCMC might be the preferred way of doing this.
- [ ] Can I tie together the photon indices of the reflection and power law models?
- [x] For plotting purposes it would be nice to rebin the data by, e.g., a factor of 10 so that the plots look less busy even though the higher resolution data are being used for fitting. I couldn't get `group_min_counts` to work for some reason. Might write a simple rebin by factor $n$ routine.

**Comment by phajy** [comment]
For the models to fit the data we need a couple of additional things:

- [ ] Higher iron abundance (I'm running a grid with $3 \times$ solar abundances)
- [ ] We need to include un-blurred, distant reflection. This is just the un-convolved reflection model. However, this needs to include the slight redshift. It would be perfect if the convolved reflection models could also be redshfited.

**Comment by phajy** [comment]
I'm trying to do a Laor versus Gradus consistency check and am not quite sure why I'm not getting good agreement. Could it be the emissivity profile? I'm trying to fit the merged XMM data alone and get the following fits (sorry the code I've uploaded more recently is a bit bad). Here are two comparison plots:

Laor model

debug_laor

Gradus convolved line only model

debug_gradus

The Laor only fit is comparable to what I get in XSPEC. The model is simply a power law plus + broad iron line (either Laor or the Gradus model). The Laor model has the line energy frozen at 6.4 keV, emissivity frozen at 3.0, r_in frozen at 1.235, r_out frozen at 400, inclination is $\sim 35$. The normalisations and photon index are free parameters.

I should directly compare the Laor and Gardus line profiles - I've not checked that yet! In any case, I think writing this has helped me :)

**Comment by phajy** [comment]
@fjebaker I _think_ [laor_comparison.jl](src/laor-comparison.jl) should produce the same line profile in two different ways but there is a discrepancy. Any idea why this might not be doing what I think it should?

laor_gradus

**Comment by phajy** [comment]
Fixed - needed to ensure we were using SpectralFitting v0.5.13

fixed

(N.B. relative normalisation is by eye).

**Comment by phajy** [comment]
And perfectly consistent with Laor model

debug_fixed

**Comment by fjebaker** [comment]
I'm wondering why the Laor model has a slightly different slope... iirc in one of Dauser's papers he compares his relline to laor and they agree very closely, and we agree very closely with relline, so am curious as to what's causing that difference.

Edit: not to investigate now, but after the conference.

**Comment by phajy** [comment]
I think I've got decent enough plots for the spin fits to justify closing and merging this branch which I will now do!

**Pull request merged**
